language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
  - 'nightly'

services:
  - memcached

matrix:
  allow_failures:
    - php: 'nightly'

before_script:
  - pecl install pcov
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - bash <(curl -s https://raw.githubusercontent.com/php-cache/cache/master/build/php/7.2/Memcached.sh)
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - if [ $(phpenv version-name) = "7.4" ]; then ./cc-test-reporter before-build; fi
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-xml=build/coverage-xml --log-junit=build/junit.xml
  - if [ $(phpenv version-name) = "7.4" ]; then ./vendor/bin/infection --coverage=build --min-msi=60 -j$(nproc); fi

after_success:
  - if [ $(phpenv version-name) = "7.4" ]; then ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT; fi
  - bash <(curl -s https://codecov.io/bash)
